### ISSUE TITLE
About RevigoR

### ISSUE THREAD

**Issue by zhaosq2016** [FelixErnst/RevigoR#3]
Hi，
When I install RevigoR, there is some error.
"**> library(RevigoR)
Error in library(RevigoR) : ‘RevigoR’ is not a valid installed package**"

Do you know the reason?

Shiqi

**Comment by FelixErnst** [comment]
Nope. Not really. I just installed it again using `remotes::install_github`

How did install it? Without as a sessionInfo output, it is also hard to get an initial clue.

**Comment by zhaosq2016** [comment]
Thank you very much
I installed it in two ways:
First way:  devtools::install_github('FelixErnst/RevigoR')
The error:"**Downloading GitHub repo FelixErnst/RevigoR@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/FelixErnst/RevigoR/tarball/master**'"

Second way: download the package and install it manually.
the error when library: "**Error in library(RevigoR) : ‘RevigoR’ is not a valid installed package**"

 I just installed it using remotes::install_github("FelixErnst/RevigoR")
the error is same as devtools::install_github

**Comment by FelixErnst** [comment]
Please provide a sessionInfo output.

You propably have a broken R installation or something is blocking access to github. It is definitively not a problem with RevigoR, but the system you are using

**Comment by zhaosq2016** [comment]
OK, I had solved this problem and installed RevigoR package.
Thank you very much !
